### ISSUE TITLE
Add back callbacks to method calls.

### ISSUE THREAD

**Issue by Pagebakers** [mondora/ddp.js#14]
Handling method calls has become quite the hassle with the current setup.

```javascript
var methodId = ddp.method("login", [myLoginParams]);
ddp.on("result", function (message) {
    if (message.id === methodId && !message.error) {
        console.log("Logged in!");
    }
});
```

Can we go back to just adding a callback to the method call?

```javascript
ddp.method("login", [myLoginParams], function(err, result) {
  if (!err) console.log('Logged in!');
});

**Comment by pscanf** [comment]
Sorry, no plan on doing that. I understand your use case, but the `1.0.0` refactor changed the behaviour to better separate the responsibilities between this library and `mondora/asteroid`. Asteroid has a higher-level API and allows you to invoke remote methods in a friendlier way:
```js
asteroidInstance.call("login", ...myLoginParams).then(/* ... */);
```
Hope you can that! :-)
Cheers

**Comment by Pagebakers** [comment]
Fair enough :)
