### ISSUE TITLE
minor doc update or minor lib update

### ISSUE THREAD

**Issue by jason-c-child** [mondora/ddp.js#17]
apparently when you sub and want to pass params you need to pass an array or arrays:

unless i'm misreading the docs for this lib, the following is the recommended pattern for passing params

```javascript
// ...client
ddpClient.sub('myCollection', [{a: 1, b: 2}, {a: 3, b: 4}])

//...server
Meteor.publish('myCollection', (params) => console.log(params))

//...output
I20151111-11:17:26.592(-8)? { a: 1, b: 2 }
```

If you wrap the array in another array it operates as expected
```javascript
// ...client
ddpClient.sub('myCollection', [[{a: 1, b: 2}, {a: 3, b: 4}]])

//...server
Meteor.publish('myCollection', (params) => console.log(params))

//...output
I20151111-11:17:26.592(-8)? [{ a: 1, b: 2 }, {a: 3, b: 4}]
```

note: i came this this conclusion by watching a 'standard' client subscription (fullstack meteor app) ddp traffic with `ddp-analyzer-proxy`

```javascript
4  OUT  1  {"msg":"sub","id":"6fjCbCQC6YZq6qhRy","name":"myCollection","params":[[{"one":1},{"two":2}, {"one":3, "two": 4]]}
```

my-2-cents: update the docs to callout array of array reqs or change [this](https://github.com/mondora/ddp.js/blob/master/src/ddp.js#L90-L99):

to

```javascript
    sub (name, params) {
        var id = uniqueId();
        this.messageQueue.push({
            msg: "sub",
            id: id,
            name: name,
            params: [params]
        });
        return id;
    }
```

...though I've no need for remote method calls so I've not tried them to see if they suffer from the same issue...if so a general doc note may be best

thx

**Comment by pscanf** [comment]
That is indeed the expected behaviour.
If on the server I have the publication:
```js
Meteor.publish("myPublication", (a, b, c) => {
    /* ... */
});
```
then on the client I subscribe to it with:
```js
ddp.sub("myPublication", ["a", "b", "c"]);
```

I have updated the docs to better clarify it. Thank you for reporting and sorry for having taken so long to respond.
