### ISSUE TITLE
Disconnect DDP

### ISSUE THREAD

**Issue by Mokto** [mondora/ddp.js#20]
Is it possible to disconnect DDP ?

Thanks.

**Comment by pscanf** [comment]
I'm working on it right now, it'll be available in the upcoming `2.0.0` release (hopefully by this afternoon).

Sorry if I take a lot of time to respond to issues. Unfortunately I'm very busy at work and I can only work on this project when "I need something from it".

**Comment by Mokto** [comment]
Nice !

Thanks. Looking forward to see this.

**Comment by pscanf** [comment]
Implemented in `2.0.0`. :-)
