### ISSUE TITLE
Informations about release 2.0.0

### ISSUE THREAD

**Issue by Mokto** [mondora/ddp.js#21]
Hi,

It would be nice to know what changed in your 2.0.0 release.

What are the breaking changes, new features, etc ?

Thank you !

**Comment by pscanf** [comment]
You can take a look at the [CHANGELOG](https://github.com/mondora/ddp.js/blob/master/CHANGELOG.md). I've edited to make it clearer what were breaking changes and what were new features.

Cheers :smiley:

**Comment by Mokto** [comment]
Thank you !
