### ISSUE TITLE
Use with react-native

### ISSUE THREAD

**Issue by Mokto** [mondora/ddp.js#24]
Hi,

Your plugin is really nice. But I have got some issues when using it with react-native.

At first, I npm install your plugin et get some issues : 
- `missing preset es2015 and stage-0`

So I install this babel presets, but now I get :
- `Cannot read property 'EventEmitter' of undefined`

It fails at this line : 
`var originalGlobalValue = exports.EventEmitter;` in EventEmitter module.

Have you got any idea ?

Thanks.

**Comment by seeekr** [comment]
`exports` would usually be defined if you were using a JS module loader at build and runtime. So look at your build and fix that, usually by following some recipe for a build for which there are many on the web. Can't be more specific than that.

**Comment by Mokto** [comment]
I didn't manage to make it work. So I have to copy your plugin into mine to be honest...

[react-native-meteor](https://github.com/mondora/ddp.js)
