### ISSUE TITLE
IE9 support

### ISSUE THREAD

**Issue by zaklampert** [mondora/ddp.js#26]
I understand that websockets are not supported in IE9, but is there a way to make ddp.js work on IE9? 

I'm getting the error `WebSocket is undefined`. How does Meteor work on IE9 if websockets are unsupported?

**Comment by pscanf** [comment]
Definitely! You just need [`sockjs-client`](https://github.com/sockjs/sockjs-client):

```js
const DDP = require("ddp.js");
const options = {
    endpoint: "http://localhost:3000/sockjs",
    SocketConstructor: SockJS
};
const ddp = new DDP(options);
```

Let me know.

**Comment by zaklampert** [comment]
Great!

Slightly more verbosely (and es6) just in case anyone else has this issue.

`npm install -s sockjs-client`

```
import DDP from "ddp.js";
import SockJS from 'sockjs-client'

const options = {
   endpoint: "http://localhost:3000/sockjs",
   SocketConstructor: SockJS
};
const ddp = new DDP(options);
```

Thanks a ton!
