### ISSUE TITLE
TypeError: object is not a function

### ISSUE THREAD

**Issue by anshv** [mondora/ddp.js#27]
TypeError: object is not a function
    at meteorInstall.server.main.js

var DDP = require("ddp");
var WebSocket = require('ws');
const options = {
    endpoint: "ws://localhost:4001/WebSocket",
    SocketConstructor: WebSocket
};

var ddp = new DDP(options); //error coming here on this line

**Comment by davidebianchi** [comment]
hi @anshv,

can you please check if you are requiring the correct `npm-modules`?
Our module is [`ddp.js`](https://www.npmjs.com/package/ddp.js).
