### ISSUE TITLE
Need to update wolfy87-eventemitter to 5.x

### ISSUE THREAD

**Issue by involve-it** [mondora/ddp.js#34]
5.x contains critical fix - "EventEmitter.js?38d3:22 Uncaught TypeError: Cannot read property 'EventEmitter' of undefined", related with bug in not passing exports object, EventEmitter.js

Without this fix ddp.js will not work with new asteroidjs (2.x)

* I created Pull Request just in case too.

**Comment by davidebianchi** [comment]
Update dependency with #38, released v2.2.1
