### ISSUE TITLE
Not able to use it with bower.

### ISSUE THREAD

**Issue by joejeet** [mondora/ddp.js#4]
ReferenceError: require is not defined
var EventEmitter = require("wolfy87-eventemitter"); At this line.

**Comment by joejeet** [comment]
Sorry closed it by mistake.

**Comment by pscanf** [comment]
There's a UMD bundle in [`dist/ddp.js`](https://github.com/mondora/ddp.js/blob/master/dist/ddp.js) now, it should work. :smiley:

**Comment by shaylevi2** [comment]
No it doesn't work.
