### ISSUE TITLE
Version on npm is out of date

### ISSUE THREAD

**Issue by emmanuelbuah** [mondora/ddp.js#7]

**Comment by emmanuelbuah** [comment]
resolved via npm git dependency reference.

**Comment by pscanf** [comment]
Hi there,

I was not publishing to npm because after the refactor I was considering bumping the version to `1.0.0` (which is drastically different from `0.6.0`). That was in January, so I guess I should do something about :smile: . If I have time I might do it later today, else feel free to bug me about. :smile: 

Thanks

**Comment by emmanuelbuah** [comment]
@pscanf  Thanks. For now, I can use git dependency reference so we should be good till you can get to it.  Question? Is the current Asteroid master branch synced but with the current ddp.js master branch? I currently working on refactoring dist/asteroid.node.js as a module to nativescript. Just wanted to make sure the current branches are on the same page.

**Comment by pscanf** [comment]
Hi @emmanuelbuah,

sorry for the delayed reply, I lost track of time :confused:.

No, unfortunately the two branches aren't in sync. `ddp.js` underwent a drastic refactoring in January, as I planned to also refactor `Asteroid` to make it more event-friendly, but alas, I never got around to do that (hopefully, some day, soon).

If you're having troubles with your refactoring, feel free to ask (we can even schedule a hangout if you want).

Let me know :-)

Cheers
pscanf

**Comment by dandv** [comment]
:+1: Found the hard way that the [npm version is 0.4.5](https://www.npmjs.com/package/ddp.js).

**Comment by dandv** [comment]
:+1: Found the hard way that the [npm version is 0.4.5](https://www.npmjs.com/package/ddp.js). On the other hand, `browserify` on a file that has `var astro = require('asteroid')` produces a 700 KB bundle file (!).

**Comment by pscanf** [comment]
Ok, I released `1.0.0`. There might be problems (I might have forgotten to do something :smiley: ). I'll try to iron them out in the next hours.

**Comment by dandv** [comment]
If I just swap the previous version of ddp.js with this one, and keep Asteroid and Q, I get `EventEmitter is not defined` at this line - https://github.com/mondora/ddp.js/blob/master/dist/ddp.js#L133

**Comment by pscanf** [comment]
Yes, `1.0.0` and `0.6.0` are not compatible. See the [CHANGELOG](https://github.com/mondora/ddp.js/blob/master/CHANGELOG.md) for details. :smiley:
